// Frozen map from v1 positional checklist ids (ck-<group>-<item>) to stable ids.
// Generated once from the v1 checklist order. Never edit: it only exists to
// migrate saved v1 progress.
export const V1_CHECKLIST_MAP: Record<string, string> = {
  "ck-0-0": "ck-explain-why-system-is-not-a",
  "ck-0-1": "ck-name-the-five-stop-reason-values",
  "ck-0-2": "ck-describe-the-cache-prefix-order-and",
  "ck-0-3": "ck-state-four-properties-of-the-batch",
  "ck-0-4": "ck-explain-when-a-cloud-vendor-endpoint",
  "ck-0-5": "ck-place-an-instruction-correctly-system-claude",
  "ck-0-6": "ck-explain-content-boundaries-and-why-user",
  "ck-0-7": "ck-define-session-hygiene-and-say-when",
  "ck-0-8": "ck-describe-safe-large-scale-refactoring-with",
  "ck-1-0": "ck-distinguish-context-window-from-max-output",
  "ck-1-1": "ck-explain-what-effort-is-and-what",
  "ck-1-2": "ck-state-the-cost-optimization-order-in",
  "ck-1-3": "ck-explain-why-thinking-tokens-are-the",
  "ck-1-4": "ck-name-what-an-sdk-adds-over",
  "ck-1-5": "ck-identify-claude-streaming-as-sse-not",
  "ck-1-6": "ck-name-three-breaking-changes-that-appear",
  "ck-1-7": "ck-distinguish-zero-single-and-multi-shot",
  "ck-2-0": "ck-state-the-workflow-versus-agent-criterion",
  "ck-2-1": "ck-name-the-five-workflow-patterns-and",
  "ck-2-2": "ck-explain-the-primary-reason-subagents-exist",
  "ck-2-3": "ck-explain-why-a-hook-beats-a",
  "ck-2-4": "ck-choose-self-hosted-vs-managed-from",
  "ck-3-0": "ck-distinguish-context-drift-from-context-bloat",
  "ck-3-1": "ck-explain-why-an-eval-set-must",
  "ck-3-2": "ck-describe-defensive-parsing-concretely",
  "ck-3-3": "ck-explain-why-truncated-output-must-not",
  "ck-4-0": "ck-explain-who-executes-a-tool",
  "ck-4-1": "ck-explain-why-tool-descriptions-are-prompts",
  "ck-4-2": "ck-name-the-three-mcp-primitives-and",
  "ck-4-3": "ck-name-the-current-mcp-transports-and",
  "ck-4-4": "ck-choose-among-built-in-tool-custom",
  "ck-5-0": "ck-name-the-structural-injection-mitigations-and",
  "ck-5-1": "ck-explain-why-a-tool-request-is",
  "ck-5-2": "ck-explain-least-privilege-for-an-agent",
  "ck-5-3": "ck-name-the-blocking-hook-event-its",
  "ck-6-0": "ck-name-claude-code-s-core-components",
  "ck-6-1": "ck-explain-description-as-trigger-in-a",
  "ck-6-2": "ck-isolate-a-failure-between-integration-layer",
  "ck-6-3": "ck-explain-why-an-llm-judge-must"
};
