// Generates the lab walkthrough pages from the notebooks.
//
//   labs/NN_slug.ipynb            source of truth for prose and code
//   labs/meta.json                title, time, cost, domains, objectives
//   labs/annotations/NN_slug.json expected outputs and "what to notice" per code cell,
//                                 keyed by cell id (or "cell-<index>" if the
//                                 notebook has no ids), plus checkpoint answers
//
// Output: src/content/labs/NN_slug.mdx (generated, do not edit) and a copy of
// each notebook in public/labs-nb/ for offline download.
//
//   npx tsx scripts/build_labs.ts           # write
//   npx tsx scripts/build_labs.ts --check   # fail if generated files are stale
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib/load.ts';

const LABS = path.join(ROOT, 'labs');
const OUT = path.join(ROOT, 'src/content/labs');
const NB_OUT = path.join(ROOT, 'public/labs-nb');
const check = process.argv.includes('--check');

type Meta = Record<
  string,
  { n: number; title: string; minutes: number; cost?: string; proves: string; domains: number[]; objectives: string[]; apiKeyNeeded: boolean; top3?: boolean }
>;
type Cell = { cell_type: 'markdown' | 'code' | 'raw'; source: string[] | string; id?: string };
type Annotation = {
  cells?: Record<string, { output?: string; kind?: 'illustrative' | 'executed'; executedAt?: string; notice?: string[]; explain?: string }>;
  checkpoint?: { q: string; a: string }[];
};

const meta = JSON.parse(fs.readFileSync(path.join(LABS, 'meta.json'), 'utf8')) as Meta;
const src = (c: Cell) => (Array.isArray(c.source) ? c.source.join('') : c.source);

/** Escape MDX-significant characters outside inline code spans. */
function mdxSafe(md: string): string {
  // Fenced code blocks pass through untouched; only prose is escaped.
  return md
    .split(/(```[\s\S]*?```)/g)
    .map((block, j) => (j % 2 ? block : escapeProse(block)))
    .join('');
}
function escapeProse(md: string): string {
  return md
    .split(/(`[^`\n]*`)/g)
    .map((part, i) => (i % 2 ? part : part.replace(/\{/g, '&#123;').replace(/\}/g, '&#125;').replace(/<(?=[A-Za-z/!])/g, '&lt;')))
    .join('');
}
const fenceSafe = (s: string) => s.replace(/```/g, '`​``');
const attr = (s: string) => s.replace(/"/g, '&quot;');

fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(NB_OUT, { recursive: true });
let stale = 0;

for (const file of fs.readdirSync(LABS).filter((f) => f.endsWith('.ipynb')).sort()) {
  const slug = file.replace(/\.ipynb$/, '');
  const m = meta[slug];
  if (!m) throw new Error(`labs/meta.json has no entry for ${slug}`);
  const raw = fs.readFileSync(path.join(LABS, file), 'utf8');
  const nb = JSON.parse(raw) as { cells: Cell[] };
  const annPath = path.join(LABS, 'annotations', `${slug}.json`);
  const annRaw = fs.existsSync(annPath) ? fs.readFileSync(annPath, 'utf8') : '{}';
  const ann = JSON.parse(annRaw) as Annotation;
  const hash = crypto.createHash('sha256').update(raw).update(annRaw).update(JSON.stringify(m)).digest('hex').slice(0, 12);

  const out: string[] = [];
  out.push('---');
  out.push(`n: ${m.n}`);
  out.push(`title: ${JSON.stringify(m.title)}`);
  out.push(`minutes: ${m.minutes}`);
  if (m.cost) out.push(`cost: ${JSON.stringify(m.cost)}`);
  out.push(`proves: ${JSON.stringify(m.proves)}`);
  out.push(`domains: [${m.domains.join(', ')}]`);
  out.push(`objectives: [${m.objectives.map((o) => JSON.stringify(o)).join(', ')}]`);
  out.push(`apiKeyNeeded: ${m.apiKeyNeeded}`);
  out.push(`top3: ${!!m.top3}`);
  out.push(`notebook: ${JSON.stringify(file)}`);
  out.push('---');
  out.push(`{/* GENERATED by scripts/build_labs.ts from labs/${file} and labs/annotations/${slug}.json. Do not edit. hash:${hash} */}`);
  out.push('');

  let codeN = 0;
  nb.cells.forEach((c, i) => {
    const text = src(c).replace(/\s+$/, '');
    if (!text) return;
    const key = c.id ?? `cell-${i}`;
    if (c.cell_type === 'markdown') {
      // Drop the notebook's own H1 (the page renders the title) and the trailing checkpoint list if answers exist.
      let md = text.replace(/^# .*\n?/, '');
      if (ann.checkpoint?.length && /###? Checkpoint/i.test(md)) md = md.replace(/-{3,}\n?/g, '').replace(/###? Checkpoint[\s\S]*$/i, '');
      if (md.trim()) out.push(mdxSafe(md.trim()), '');
      return;
    }
    if (c.cell_type !== 'code') return;
    codeN++;
    out.push('```python', fenceSafe(text), '```', '');
    const a = ann.cells?.[key];
    if (a?.output) {
      out.push(`<Output kind="${a.kind ?? 'illustrative'}"${a.executedAt ? ` date="${attr(a.executedAt)}"` : ''} label="Out [${codeN}]">`);
      out.push('', '```text', fenceSafe(a.output.replace(/\s+$/, '')), '```', '', '</Output>', '');
    }
    if (a?.notice?.length) {
      out.push('**What to notice**', '');
      for (const n of a.notice) out.push(`- ${mdxSafe(n)}`);
      out.push('');
    }
    if (a?.explain) out.push(mdxSafe(a.explain), '');
  });

  if (ann.checkpoint?.length) {
    out.push('## Checkpoint', '');
    for (const c of ann.checkpoint) out.push(`<Recall q="${attr(c.q)}">`, '', mdxSafe(c.a), '', '</Recall>', '');
  }

  const mdx = out.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';
  const target = path.join(OUT, `${slug}.mdx`);
  const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (existing !== mdx) {
    stale++;
    if (!check) fs.writeFileSync(target, mdx);
  }
  if (!check) fs.copyFileSync(path.join(LABS, file), path.join(NB_OUT, file));
}

if (check && stale) {
  console.error(`FAIL: ${stale} generated lab page(s) are stale. Run: npx tsx scripts/build_labs.ts`);
  process.exit(1);
}
console.log(check ? 'PASS: lab pages are current' : `labs: wrote ${stale} page(s)`);
